image: node:14.16.0

pipelines:
  branches:
    release/test:
          - step:
              name: 'Build and Test'
              deployment: test
              script:
                  - echo $NEXT_PUBLIC_BACKEND_URL
                  - yarn
                  - yarn build
                  - apt-get update && apt-get install -y
                  - apt-get install zip
                  - zip -r application.zip .next package.json
              artifacts:
                  - application.zip
          - step:
              name: 'Deploy to Test'
              script:
                  - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
                    variables:
                        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                        AWS_DEFAULT_REGION: '$AWS_DEFAULT_REGION'
                        APPLICATION_NAME: '$APPLICATION_NAME'
                        NPM_TOKEN: '$NPM_TOKEN'
                        ENVIRONMENT_NAME: 'Bptk-dashboard-showcase-env'
                        S3_BUCKET: 'elasticbeanstalk-eu-central-1-729621526906'
                        ZIP_FILE: 'application.zip'
                        WAIT: 'true'
    release/prod:
          - step:
              name: 'Build and Test'
              deployment: production
              script:
                  - echo $NEXT_PUBLIC_BACKEND_URL
                  - yarn
                  - yarn build
                  - apt-get update && apt-get install -y
                  - apt-get install zip
                  - zip -r application.zip .next package.json
              artifacts:
                  - application.zip
          - step:
              name: 'Deploy to Prod'
              script:
                  - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
                    variables:
                        AWS_ACCESS_KEY_ID: $PROD_AWS_ACCESS_KEY_ID
                        AWS_SECRET_ACCESS_KEY: $PROD_AWS_SECRET_ACCESS_KEY
                        AWS_DEFAULT_REGION: '$PROD_AWS_DEFAULT_REGION'
                        APPLICATION_NAME: '$PROD_AWS_APPLICATION_NAME'
                        NPM_TOKEN: '$NPM_TOKEN'
                        ENVIRONMENT_NAME: '$PROD_AWS_ENVIRONMENT_NAME'
                        ZIP_FILE: 'application.zip'
                        WAIT: 'true'
