image: node:14.16.0

pipelines:
    default:
        - step:
              name: 'Build and Test'
              script:
                  - yarn
                  - yarn build
                  - apt-get update && apt-get install -y
                  - apt-get install zip
                  - zip application.zip .next
              artifacts:
                  - application.zip
        - step:
              name: 'Deploy to Production'
              # Track production environments builds using deployments.
              deployment: production
              script:
                  - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
                    variables:
                        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                        AWS_DEFAULT_REGION: '$AWS_DEFAULT_REGION'
                        APPLICATION_NAME: '$APPLICATION_NAME'
                        ENVIRONMENT_NAME: 'dev'
                        ZIP_FILE: 'application.zip'
