name: Dev Build to Dockerhub

on:
    create:
        tags:
            - v*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Get the Tagged version
              id: get_version
              run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
            - name: Create and Build Dockercontainer
              uses: docker/build-push-action@v2
              with:
                  context: .
                  tags: transentis/sim-covid-dashboard:${{ steps.get_version.outputs.VERSION  }}
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Push Dockercontainer
              run: docker push transentis/sim-covid-dashboard:${{ steps.get_version.outputs.VERSION  }}
